version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend-code:/usr/share/nginx/html
    networks:
      - frontend-backend-network
    environment:
      - NGINX_HOST=service.frontend.example.com
      - NGINX_PORT=80
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - backend-code:/app
    ports:
      - "8080:8080"
    networks:
      - frontend-backend-network
    environment:
      - API_KEY=your_api_key
networks:
  frontend-backend-network:
    driver: bridge
volumes:
  frontend-code:
  backend-code: